databases:
  - name: piazza-db
    databaseName: piazza
    region: singapore

services:
  - type: redis
    name: piazza-cache
    ipAllowList: []
    maxmemoryPolicy: allkeys-lfu
    region: singapore

  - type: web
    name: piazza-web
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    region: singapore
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: piazza-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: piazza-cache
          property: connectionString
